### ISSUE TITLE
Getting problem: [Exception] Invalid timestamp

### ISSUE THREAD

**Issue by nielsonsantana** [bloomreach/s4cmd#83] opened 2016-09-13 14:42 UTC
I'm using the version 2.0.1 and getting '[Exception] Invalid timestamp "Thu, 13 Sep 2018 13:28:18 -0000 GMT": Unknown string format' when I try synchronise the static files.
The command that I run:

`s4cmd sync --recursive parceiros/assets s3://$AWS_BUCKET_NAME/static 
 --access-key=$AWS_ACCESS_KEY_ID --secret-key=$AWS_SECRET_ACCESS_KEY`

**Comment by nielsonsantana** [comment] 2016-09-13 15:44
The problem occur after call of lokkup.

```
def lookup(self, s3url):
    '''Get the s3 object with the S3 URL. Return None if not exist.'''
    return self.s3.head_object(Bucket=s3url.bucket, Key=s3url.path)
```

Full track of bug.

```
  (D)s4cmd.py:134  >> upload(<ThreadUtil(Thread-1, started daemon 140603768776448)>, 'parceiros/assets/admin/img/changelist-bg.gif', 's3://genomika-parceiros-staging-assets/static/admin/img/changelist-bg.gif')
  (D)s4cmd.py:134  >> lookup(<ThreadUtil(Thread-1, started daemon 140603768776448)>, <__main__.S3URL instance at 0x7fe0ddb21ab8>)
  (D)s4cmd.py:1271 <function wrapped_method at 0x7fe0ddbb3230>
  (D)s4cmd.py:404  >> S3APICALL head_object(Bucket='genomika-parceiros-staging-assets', Key='static/admin/img/changelist-bg.gif')
  (D)s4cmd.py:136  << put_single_file(<__main__.S3Handler object at 0x7fe0de0d6890>, <__main__.ThreadPool object at 0x7fe0de0094d0>, 'parceiros/assets', 's3://genomika-parceiros-staging-assets/static'): None
Header infor returned
{'content-length': '50', 'x-amz-id-2': 'lZui+clJBEaifYIjEKfH6JIbPTMXfHgNYkxMFWUuhkgGmo2egfbKYeuDjXYkyx9OwnIHUf0ZLTQ=', 'accept-ranges': 'bytes', 'expires': 'Thu, 13 Sep 2018 13:28:18 -0000 GMT', 'server': 'AmazonS3', 'last-modified': 'Tue, 13 Sep 2016 13:28:19 GMT', 'x-amz-request-id': '6C56EA439FEAB1FE', 'etag': '"eaa563daae2a1fc7069501a38b4d6467"', 'cache-control': 'max-age 63072000', 'date': 'Tue, 13 Sep 2016 15:28:26 GMT', 'content-type': 'image/gif'}

Exception in thread Thread-1:aining, 1 thread(s)]
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/s4cmd.py", line 524, in run
    self.__class__.__dict__[func_name](self, *args, **kargs)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/s4cmd.py", line 135, in wrapper
    ret = func(*args, **kargs)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/s4cmd.py", line 1295, in upload
    obj = self.lookup(s3url)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/s4cmd.py", line 135, in wrapper
    ret = func(*args, **kargs)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/s4cmd.py", line 1272, in lookup
    return self.s3.head_object(Bucket=s3url.bucket, Key=s3url.path)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/s4cmd.py", line 405, in wrapped_method
    ret = getattr(self.client, method)(*args, **merged_kargs)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/botocore/client.py", line 159, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/botocore/client.py", line 483, in _make_api_call
    operation_model, request_dict)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/botocore/endpoint.py", line 117, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/botocore/endpoint.py", line 144, in _send_request
    request, operation_model, attempts)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/botocore/endpoint.py", line 209, in _get_response
    response_dict, operation_model.output_shape)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/botocore/parsers.py", line 212, in parse
    parsed = self._do_parse(response, shape)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/botocore/parsers.py", line 603, in _do_parse
    member_shapes, final_parsed)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/botocore/parsers.py", line 659, in _parse_non_payload_attrs
    member_shape, headers[header_name])
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/botocore/parsers.py", line 259, in _parse_shape
    return handler(shape, node)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/botocore/parsers.py", line 149, in _get_text_content
    return func(self, shape, text)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/botocore/parsers.py", line 413, in _handle_timestamp
    return self._timestamp_parser(text)
  File "/home/nsantana/.virtualenvs/parceiros/lib/python2.7/site-packages/botocore/utils.py", line 336, in parse_timestamp
    raise ValueError('Invalid timestamp "%s": %s' % (value, e))
ValueError: Invalid timestamp "Thu, 13 Sep 2018 13:28:18 -0000 GMT": Unknown string format

```

**Comment by pako-pl** [comment] 2016-11-06 09:41
AWS SDK requires the system clock to be set to correct time to compute the signatures.

**Comment by navinpai** [comment] 2018-05-21 19:41
Since this fix is to either fix system time or a fix from boto3 side, marking it as invalid and closing it out.

If you continue seeing the issue, please let me know (or probably report it to the boto project)

**Closed by navinpai** 2018-05-21 19:41 UTC
Labels: invalid, wontfix

**Comment by suavesav** [comment] 2021-07-01 01:28
The issue is in the metadata of the file you are trying to sync. The field with the invalid timestamp object will need to be removed or updated.

The other solution is so use awscli v1

At some point this was the recommended timestamp format, but it is no longer supported in boto3
