### ISSUE TITLE
What about excluding directories?

### ISSUE THREAD

**Issue by illectronic** [bloomreach/s4cmd#31] opened 2015-06-18 19:42 UTC
We have directories such as .svn which we don't want uploaded. Would you consider adding include/exclude?

Thanks.

**Comment by ixodie** [comment] 2015-06-22 18:21
We'd love to try this but we need --exclude-from like in s3cmd.

Thanks!

**Comment by illectronic** [comment] 2015-06-26 17:45
I am already trying to custom code it but I am running into a lot of issues on the s3walk side.

**Comment by ixodie** [comment] 2015-06-26 17:46
Yeah, this is a must have feature.

**Comment by chouhanyang** [comment] 2016-05-12 00:35
It is kind of tricky because comparing two directory path with the possibility of trailing slashes, relative/absolution paths whiling recursive walk into the directory. Maybe you can try to catch this after s3walk first (while sorting the final output) and then gradually improving the efficiency?

**Comment by dannyman** [comment] 2016-08-26 23:59
+1

**Comment by navinpai** [comment] 2018-08-13 23:32
Closing this as a dupe of #88 (as that's to support a superset exclude and include dir feature so it's easier to track in one issue).

**Closed by navinpai** 2018-08-13 23:32 UTC
Labels: feature-request
