### ISSUE TITLE
S4cmd not working for DreamObjects or Other object storage services.

### ISSUE THREAD

**Issue by srinivas245** [bloomreach/s4cmd#93] opened 2016-12-31 02:01 UTC
I just switched from `s3cmd` to `s4cmd`. It's working great for EC2 to Amazon S3 data transfer. But when I'm trying DreamObjects or CenturyLink Object storage in it's place, it shows the below error:

`ClientError: An error occurred (InvalidAccessKeyId) when calling the ListBuckets operation: The AWS Access Key Id you provided does not exist in our records.`

I properly configured `.s3cfg` for DreamObjects, I know it because when I type `s3cmd ls` it lists the buckets. But when I type `s4cmd ls` it gives the above error.

So is s4cmd not compatible with other object storage services currently?

**Comment by vchrisb** [comment] 2017-01-24 14:57
had the same issue and it looks like s4cmd does not support the ```endpoint_url``` parameter. 
There is a merge request though: #82

**Comment by navinpai** [comment] 2018-05-21 20:00
Dupe of #107 

----
A pullrequest doing just this was merged into master a couple days back (#82 ). Should be fine to work with any endpoint using --endpoint-url. We're in the process of updating our test-suite to use minio to ensure this works E2E, but you can play around with it in the meantime! (You'll have to build from the latest code until we update pip et al)

Closing this issue for now, but let me know if you face any issues and I'll reopen it! :D

**Closed by navinpai** 2018-05-21 20:00 UTC
Labels: duplicate

**Comment by Xp0is0nX** [comment] 2018-05-23 15:44
Hi,
while "ls" operation seems to be working, "put" doesn't and end up with:

[Exception] Parameter validation failed:
Invalid length for parameter Key, value: 0, valid range: 1-inf
[Thread Failure] Parameter validation failed:
Invalid length for parameter Key, value: 0, valid range: 1-inf

**Comment by BrookeDot** [comment] 2019-12-28 06:56
@Xp0is0nX I had that problem too but adding a `/` to the end of my bucket seemed to fix it. Ie `s3://backups/` instead of `s3://backups`. You may have moved on but thought this may be worth mentioning.
