### ISSUE TITLE
exclude parameter is missing in s4cmd

### ISSUE THREAD

**Issue by dixitgoyal** [bloomreach/s4cmd#129] opened 2018-08-11 10:16 UTC

**Comment by navinpai** [comment] 2018-08-13 23:34
Hey,
Thanks for the feature request. This is a dupe of #88 . Closing this issue as it'll be easier to track the feature in a single issue . Pull requests always welcome if you'd like to contribute! :)

**Closed by navinpai** 2018-08-13 23:34 UTC
Labels: feature-request
